---
swagger: "2.0"
info:
  description: "A location classifier microservice. Leverages multiple Foursquare\
    \ APIs to deliver confident categorization of location queries.\n\nBuilt with\
    \ [aiohttp](http://aiohttp.readthedocs.io/en/stable/index.html), source code available\
    \ on [Github](https://github.com/chrislawlor/classify-server)"
  version: "1.2.0"
  title: "Location Data Classifier"
  termsOfService: ""
  contact:
    name: "Chris Lawlor"
  license:
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0"
host: "example.com"
basePath: "/v1"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /foursquare/category:
    get:
      tags:
      - "Companies"
      summary: "Load the list of Companies"
      description: "Loads a list of Company"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
        description: "The name of the location"
        x-example: "Flatiron Building"
      - name: "lat"
        in: "query"
        required: true
        type: "number"
        description: "Latitude"
        x-example: 0.7411
      - name: "lon"
        in: "query"
        required: true
        type: "number"
        description: "Longitude"
        x-example: 73.9897
      responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
            description: "{\n    \"query\": \"flatiron building\",\n    \"checkin\"\
              : null,\n    \"match\": {\n        \"id\": \"51f920698bbd3fa011813851\"\
              ,\n        \"name\": \"Flatiron Building\",\n        \"contact\": {\n\
              \            \"phone\": \"8882870086\",\n            \"formattedPhone\"\
              : \"(888) 287-0086\",\n            \"twitter\": \"skylinenyctours\"\n\
              \        },\n        \"location\": {\n            \"address\": \"175\
              \ 5th Ave\",\n            \"crossStreet\": \"5th Ave & W 23rd St\",\n\
              \            \"lat\": 40.74109555804945,\n            \"lng\": -73.98959398269653,\n\
              \            \"labeledLatLngs\": [\n                {\n            \
              \        \"label\": \"display\",\n                    \"lat\": 40.74109555804945,\n\
              \                    \"lng\": -73.98959398269653\n                }\n\
              \            ],\n            \"distance\": 8,\n            \"postalCode\"\
              : \"10010\",\n            \"cc\": \"US\",\n            \"city\": \"\
              New York\",\n            \"state\": \"NY\",\n            \"country\"\
              : \"United States\",\n            \"formattedAddress\": [\n        \
              \        \"175 5th Ave (5th Ave & W 23rd St)\",\n                \"\
              New York, NY 10010\",\n                \"United States\"\n         \
              \   ]\n        },\n        \"categories\": [\n            {\n      \
              \          \"id\": \"4bf58dd8d48988d130941735\",\n                \"\
              name\": \"Building\",\n                \"pluralName\": \"Buildings\"\
              ,\n                \"shortName\": \"Building\",\n                \"\
              icon\": {\n                    \"prefix\": \"https://ss3.4sqi.net/img/categories_v2/building/default_\"\
              ,\n                    \"suffix\": \".png\"\n                },\n  \
              \              \"primary\": true\n            }\n        ],\n      \
              \  \"verified\": true,\n        \"stats\": {\n            \"checkinsCount\"\
              : 30521,\n            \"usersCount\": 2451,\n            \"tipCount\"\
              : 129\n        },\n        \"venueRatingBlacklisted\": true,\n     \
              \   \"beenHere\": {\n            \"lastCheckinExpiredAt\": 0\n     \
              \   },\n        \"storeId\": \"\",\n        \"referralId\": \"v-1507300566\"\
              ,\n        \"venueChains\": [\n            {\n                \"id\"\
              : \"5568f4a2a7c8a9cf8ec49626\"\n            }\n        ],\n        \"\
              hasPerk\": false\n    },\n    \"category\": {\n        \"id\": \"4bf58dd8d48988d130941735\"\
              ,\n        \"name\": \"Building\",\n        \"pluralName\": \"Buildings\"\
              ,\n        \"shortName\": \"Building\",\n        \"icon\": {\n     \
              \       \"prefix\": \"https://ss3.4sqi.net/img/categories_v2/building/default_\"\
              ,\n            \"suffix\": \".png\"\n        },\n        \"primary\"\
              : true\n    }\n}"
          headers:
            Content-Type:
              type: "string"
              x-example: "application/json"
        400:
          description: "Status 400"
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  HTTP_BASIC:
    description: "All GET methods are public, meaning that *you can read all the data*.\
      \ Write operations require authentication and therefore are forbidden to the\
      \ general public."
    type: "basic"
definitions:
  CategoryResult:
    type: "object"
    properties:
      query:
        type: "string"
        description: "The location name from the query"
      checkin:
        type: "object"
        description: "Checkin response from Foursquare"
      match:
        type: "object"
        description: "Match response from Foursquare"
      category:
        type: "object"
        description: "The category"
    description: "A location category query result"
    example: "{\n    \"query\": \"flatiron building\",\n    \"checkin\": null,\n \
      \   \"match\": {\n        \"id\": \"51f920698bbd3fa011813851\",\n        \"\
      name\": \"Flatiron Building\",\n        \"contact\": {\n            \"phone\"\
      : \"8882870086\",\n            \"formattedPhone\": \"(888) 287-0086\",\n   \
      \         \"twitter\": \"skylinenyctours\"\n        },\n        \"location\"\
      : {\n            \"address\": \"175 5th Ave\",\n            \"crossStreet\"\
      : \"5th Ave & W 23rd St\",\n            \"lat\": 40.74109555804945,\n      \
      \      \"lng\": -73.98959398269653,\n            \"labeledLatLngs\": [\n   \
      \             {\n                    \"label\": \"display\",\n             \
      \       \"lat\": 40.74109555804945,\n                    \"lng\": -73.98959398269653\n\
      \                }\n            ],\n            \"distance\": 8,\n         \
      \   \"postalCode\": \"10010\",\n            \"cc\": \"US\",\n            \"\
      city\": \"New York\",\n            \"state\": \"NY\",\n            \"country\"\
      : \"United States\",\n            \"formattedAddress\": [\n                \"\
      175 5th Ave (5th Ave & W 23rd St)\",\n                \"New York, NY 10010\"\
      ,\n                \"United States\"\n            ]\n        },\n        \"\
      categories\": [\n            {\n                \"id\": \"4bf58dd8d48988d130941735\"\
      ,\n                \"name\": \"Building\",\n                \"pluralName\":\
      \ \"Buildings\",\n                \"shortName\": \"Building\",\n           \
      \     \"icon\": {\n                    \"prefix\": \"https://ss3.4sqi.net/img/categories_v2/building/default_\"\
      ,\n                    \"suffix\": \".png\"\n                },\n          \
      \      \"primary\": true\n            }\n        ],\n        \"verified\": true,\n\
      \        \"stats\": {\n            \"checkinsCount\": 30521,\n            \"\
      usersCount\": 2451,\n            \"tipCount\": 129\n        },\n        \"venueRatingBlacklisted\"\
      : true,\n        \"beenHere\": {\n            \"lastCheckinExpiredAt\": 0\n\
      \        },\n        \"storeId\": \"\",\n        \"referralId\": \"v-1507300566\"\
      ,\n        \"venueChains\": [\n            {\n                \"id\": \"5568f4a2a7c8a9cf8ec49626\"\
      \n            }\n        ],\n        \"hasPerk\": false\n    },\n    \"category\"\
      : {\n        \"id\": \"4bf58dd8d48988d130941735\",\n        \"name\": \"Building\"\
      ,\n        \"pluralName\": \"Buildings\",\n        \"shortName\": \"Building\"\
      ,\n        \"icon\": {\n            \"prefix\": \"https://ss3.4sqi.net/img/categories_v2/building/default_\"\
      ,\n            \"suffix\": \".png\"\n        },\n        \"primary\": true\n\
      \    }\n}"
  Error:
    type: "object"
    properties:
      error:
        type: "string"
        description: "The description of the error that occured."
    description: "This general error structure is used throughout this API."
    example: "{\n  \"error\": \"Bad query parameter [$size]: Invalid integer value\
      \ [abc]\"\n}"
    x-restlet:
      section: "General"
x-restlet:
  sections:
    General: {}
    About: {}
  texts:
    dpfogvi:
      title: "Authentication"
      content: "This API is secured using Basic Authentication.\n\nAll **read operations\
        \ are open** and don't require authentication."
      section: "General"
    wb9ms4i:
      title: "Error handling"
      content: "This API uses standard HTTP status codes to indicate the status of\
        \ a response.\n\nThere are two main categories of error responses. Each have\
        \ a different response payload structure.\n\n* Simple errors\n* Detailed errors\n\
        \n\n# Simple errors\n\n| Name | Code | Description |\n| -------- | --------\
        \ | -------- |\n| Bad request     | 400     | The request was unacceptable\
        \     |\n| Unauthorized     | 401     | The request has not been applied because\
        \ it lacks valid authentication credentials for the target resource.     |\n\
        | Forbidden     | 403     | The server understood the request, but is refusing\
        \ to fulfill it     |\n| Not Found     | 404     | The server has not found\
        \ anything matching the request URI     |\n| Not acceptable     | 406    \
        \ | The server is unable to return a response in the format that was requested\
        \ by the client     |\n| Unsupported Media Type     | 415     | The server\
        \ is refusing to service the request because the entity of the request is\
        \ in a format not supported by the requested resource for the requested method\
        \     |\n| Too many requests     | 429     | Too many requests hit the API\
        \ too quickly     |\n| Server error     | 500     | A technical error occured\
        \ in Restlet Cloud     |\n\n\n\n\n\n\n# Detailed errors\n| Name | Code | Description\
        \ |\n| -------- | -------- | -------- |\n| Unprocessable entity     | 422\
        \     | The server understands the content type of the request entity, and\
        \ the syntax of the request entity is correct, but was unable to process the\
        \ contained instructions.     |\n\n\n\n\n"
      section: "General"
    hm8ia4i:
      title: "Docs designed and hosted with Restlet Studio"
      content: "This API was designed and documented using [Restlet Studio](https://studio.restlet.com/).\
        \ \n\nHead over to Restlet Studio now to design your API documentation for\
        \ free.\n\n![](https://thecontactsapi.apispark.net/v1/img/studio_right_dark_64.png)"
      section: "About"
